version: 2.1

orbs:
  python: circleci/python@2.1.1

jobs:
  execute-script:
    parameters:
      app-directory:
        type: string
    docker:
      # next-gen ubuntu image
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run:
          name: execute script
          command: |
            cd << parameters.app-directory >>
            chmod +x service.sh
            ./service.sh

# the default pipeline parameters, which will be updated according to
# the results of the path-filtering orb
parameters:
  run-build-service-1-job:
    type: boolean
    default: false
  run-build-service-2-job:
    type: boolean
    default: false
# here we specify our workflows, most of which are conditionally
# executed based upon pipeline parameter values. Each workflow calls a
# specific job defined above, in the jobs section.
workflows:
  # when pipeline parameter, run-build-service-1-job is true, the
  # build-service-1 job is triggered.
  service-1:
    when: << pipeline.parameters.run-build-service-1-job >>
    jobs:
      - execute-script:
          name: build-service-1
          app-directory: service1
  # when pipeline parameter, run-build-service-2-job is true, the
  # build-service-2 job is triggered.
  service-2:
    when: << pipeline.parameters.run-build-service-2-job >>
    jobs:
      - execute-script:
          name: build-service-2
          app-directory: service2